import { type AdminRole } from "@/lib/admin-roles"

function relativeDate(dayOffset: number, hour: number, minute: number) {
  const date = new Date()
  date.setHours(hour, minute, 0, 0)
  date.setDate(date.getDate() + dayOffset)
  return date.toISOString()
}

function currentMonthDate(dayOfMonth: number, hour: number, minute: number) {
  const now = new Date()
  const date = new Date(now.getFullYear(), now.getMonth(), Math.max(1, dayOfMonth), hour, minute, 0, 0)
  return date.toISOString()
}

function buildDemoConversation(baseDayOffset: number, messages: Array<{ role: "assistant" | "user"; content: string; minuteOffset: number }>) {
  return messages.map((message) => ({
    role: message.role,
    content: message.content,
    timestamp: relativeDate(baseDayOffset, 9, message.minuteOffset),
  }))
}

function createDemoConversationFixtures() {
  return {
    "DEMO-001": {
      conversationSummary:
        "Moka detectó interés en agenda y recordatorios, cualificó el caso y abrió el siguiente paso con la calculadora ROI para orientar mejor la demo.",
      conversationMessages: buildDemoConversation(-2, [
        { role: "user", content: "Hola, quiero ver cómo automatizáis recordatorios y reservas para una clínica veterinaria.", minuteOffset: 5 },
        { role: "assistant", content: "Soy Moka. Si te parece, revisamos tu caso y te propongo una demo breve con ejemplos reales para tu agenda.", minuteOffset: 7 },
        { role: "user", content: "Perfecto. Me interesa sobre todo reducir llamadas de confirmación y huecos perdidos.", minuteOffset: 11 },
        { role: "assistant", content: "Tiene sentido. Ya tengo contexto suficiente para proponerte una demo consultiva. Te abro la calculadora ROI para orientar el siguiente paso y que elijas hueco en el calendario.", minuteOffset: 17 },
      ]),
    },
    "DEMO-007": {
      conversationSummary:
        "La clínica pidió ayuda con recordatorios de vacunas y revisiones. Moka confirmó el caso, validó el interés y abrió el paso del ROI para preparar la demo.",
      conversationMessages: buildDemoConversation(-1, [
        { role: "user", content: "Tenemos mucho volumen de vacunas y se nos escapan revisiones. Quiero ver si esto nos encaja.", minuteOffset: 2 },
        { role: "assistant", content: "Sí, Clinvetia puede automatizar ese seguimiento y priorizar respuestas. Si quieres, vemos tu caso y te abro el flujo de ROI para preparar una demo.", minuteOffset: 4 },
        { role: "user", content: "Sí, enséñamelo con un caso de primeras visitas y recordatorios.", minuteOffset: 8 },
        { role: "assistant", content: "Perfecto. El siguiente paso es abrir la calculadora ROI y luego podrás elegir en calendario una demo el viernes a las 19:00 si te encaja.", minuteOffset: 12 },
      ]),
    },
    "DEMO-010": {
      conversationSummary:
        "El lead quería validar un piloto comercial. Moka llevó la conversación desde la necesidad de activación hasta abrir el ROI y dejar preparado el camino hacia la demo con enfoque multi-canal.",
      conversationMessages: buildDemoConversation(0, [
        { role: "user", content: "Queremos captar más primeras consultas y no perder leads por WhatsApp fuera de horario.", minuteOffset: 10 },
        { role: "assistant", content: "Podemos ayudarte con captación, seguimiento y automatización comercial. Lo mejor es ver tu caso en una demo breve.", minuteOffset: 13 },
        { role: "user", content: "Vale, si en la demo vemos también seguimiento comercial y reporting, me interesa.", minuteOffset: 17 },
        { role: "assistant", content: "Perfecto. Te abro la calculadora ROI para enfocar bien el caso y después eliges en calendario la demo de la próxima semana a las 16:00 si os encaja.", minuteOffset: 22 },
      ]),
    },
  } as const
}

function createDemoBookingFixtures() {
  return [
  {
    id: "DEMO-001",
    contactId: "CNT-001",
    date: relativeDate(0, 10, 0),
    time: "10:00",
    duration: 30,
    status: "confirmed",
    nombre: "Dra. Ana Martín",
    telefono: "+34 612 345 678",
    clinica: "Clínica Central",
    email: "ana@clinicacentral.com",
    createdAt: relativeDate(-2, 9, 15),
    emailEvents: [
      {
        category: "booking_confirmed",
        subject: "Confirmación de demo ClinvetIA",
        intendedRecipient: "ana@clinicacentral.com",
        deliveredTo: "ana@clinicacentral.com",
        status: "sent",
        error: null,
        message: "Confirmación enviada correctamente.",
        sentAt: relativeDate(-2, 9, 17),
      },
    ],
  },
  {
    id: "DEMO-002",
    contactId: "CNT-002",
    date: relativeDate(0, 12, 30),
    time: "12:30",
    duration: 30,
    status: "pending",
    nombre: "Dr. Luis Pérez",
    telefono: "+34 611 222 333",
    clinica: "Vet Norte",
    email: "luis@vetnorte.es",
    createdAt: relativeDate(-1, 10, 30),
    emailEvents: [],
  },
  {
    id: "DEMO-003",
    contactId: "CNT-003",
    date: relativeDate(0, 17, 30),
    time: "17:30",
    duration: 45,
    status: "confirmed",
    nombre: "Dra. Marta Ruiz",
    telefono: "+34 644 111 000",
    clinica: "Hospital Vet Sur",
    email: "direccion@hospitalvetsur.com",
    createdAt: relativeDate(-1, 12, 20),
    emailEvents: [
      {
        category: "booking_confirmed",
        subject: "Demo confirmada para hoy",
        intendedRecipient: "direccion@hospitalvetsur.com",
        deliveredTo: "direccion@hospitalvetsur.com",
        status: "failed",
        error: "SMTP timeout (simulado)",
        message: "Reintentar envío manual.",
        sentAt: relativeDate(-1, 7, 40),
      },
    ],
  },
  {
    id: "DEMO-012",
    contactId: "CNT-012",
    date: relativeDate(0, 19, 0),
    time: "19:00",
    duration: 30,
    status: "cancelled",
    nombre: "Clínica Nova",
    telefono: "+34 621 987 654",
    clinica: "Nova Pets",
    email: "agenda@novapets.es",
    createdAt: relativeDate(0, 12, 45),
    emailEvents: [
      {
        category: "booking_cancelled",
        subject: "Cancelación de demo para hoy",
        intendedRecipient: "agenda@novapets.es",
        deliveredTo: "agenda@novapets.es",
        status: "sent",
        error: null,
        message: "Cancelación enviada correctamente.",
        sentAt: relativeDate(0, 12, 50),
      },
    ],
  },
  {
    id: "DEMO-013",
    contactId: "CNT-013",
    date: relativeDate(0, 14, 0),
    time: "14:00",
    duration: 30,
    status: "confirmed",
    nombre: "Clínica Horizonte",
    telefono: "+34 622 778 991",
    clinica: "Horizonte Vet",
    email: "direccion@horizontevet.es",
    createdAt: relativeDate(0, 9, 5),
    emailEvents: [],
  },
  {
    id: "DEMO-014",
    contactId: "CNT-014",
    date: relativeDate(0, 15, 30),
    time: "15:30",
    duration: 30,
    status: "pending",
    nombre: "Dr. Sergio Molina",
    telefono: "+34 611 808 707",
    clinica: "Molina Animal",
    email: "sergio@molinaanimal.es",
    createdAt: relativeDate(0, 9, 40),
    emailEvents: [],
  },
  {
    id: "DEMO-004",
    contactId: "CNT-004",
    date: relativeDate(1, 11, 30),
    time: "11:30",
    duration: 30,
    status: "confirmed",
    nombre: "Clínica Aurora",
    telefono: "+34 622 001 110",
    clinica: "Aurora Vet",
    email: "gerencia@auroravet.es",
    createdAt: relativeDate(-1, 13, 0),
    emailEvents: [],
  },
  {
    id: "DEMO-005",
    contactId: "CNT-005",
    date: relativeDate(-1, 16, 30),
    time: "16:30",
    duration: 30,
    status: "expired",
    nombre: "Centro Vet Levante",
    telefono: "+34 633 444 777",
    clinica: "Levante Pets",
    email: "info@levantepets.es",
    createdAt: relativeDate(-3, 16, 40),
    emailEvents: [],
  },
  {
    id: "DEMO-015",
    contactId: "CNT-015",
    date: relativeDate(-1, 11, 0),
    time: "11:00",
    duration: 30,
    status: "rescheduled",
    nombre: "Clínica Sierra",
    telefono: "+34 623 456 780",
    clinica: "Sierra Vet",
    email: "direccion@sierravet.es",
    createdAt: relativeDate(-2, 18, 10),
    emailEvents: [],
  },
  {
    id: "DEMO-016",
    contactId: "CNT-016",
    date: relativeDate(3, 10, 30),
    time: "10:30",
    duration: 30,
    status: "rescheduled",
    nombre: "Clínica Sierra",
    telefono: "+34 623 456 780",
    clinica: "Sierra Vet",
    email: "direccion@sierravet.es",
    createdAt: relativeDate(0, 10, 5),
    emailEvents: [
      {
        category: "booking_confirmed",
        subject: "Tu demo está confirmada",
        intendedRecipient: "direccion@sierravet.es",
        deliveredTo: "direccion@sierravet.es",
        status: "sent",
        error: null,
        message: "Nueva cita creada tras una expiración previa.",
        sentAt: relativeDate(0, 10, 6),
      },
    ],
  },
  {
    id: "DEMO-006",
    contactId: "CNT-006",
    date: relativeDate(2, 18, 0),
    time: "18:00",
    duration: 60,
    status: "pending",
    nombre: "Dr. Pablo Ortega",
    telefono: "+34 600 999 123",
    clinica: "Ortega Animal Care",
    email: "pablo@ortegaanimal.com",
    createdAt: relativeDate(-1, 8, 45),
    emailEvents: [],
  },
  {
    id: "DEMO-007",
    contactId: "CNT-007",
    date: relativeDate(3, 19, 0),
    time: "19:00",
    duration: 30,
    status: "confirmed",
    nombre: "Dra. Carla Ibañez",
    telefono: "+34 620 202 202",
    clinica: "Clínica Vet Costa",
    email: "carla@vetcosta.es",
    createdAt: relativeDate(-1, 10, 5),
    emailEvents: [
      {
        category: "booking_confirmed",
        subject: "Enlace de videollamada para tu demo",
        intendedRecipient: "carla@vetcosta.es",
        deliveredTo: "carla@vetcosta.es",
        status: "sent",
        error: null,
        message: "Correo entregado.",
        sentAt: relativeDate(-1, 10, 6),
      },
    ],
  },
  {
    id: "DEMO-008",
    contactId: "CNT-008",
    date: relativeDate(5, 12, 0),
    time: "12:00",
    duration: 45,
    status: "confirmed",
    nombre: "Grupo Veterinario Atlántico",
    telefono: "+34 699 101 101",
    clinica: "Atlántico Vet",
    email: "direccion@atlanticovet.com",
    createdAt: relativeDate(-1, 11, 50),
    emailEvents: [],
  },
  {
    id: "DEMO-009",
    contactId: "CNT-009",
    date: relativeDate(1, 9, 30),
    time: "09:30",
    duration: 30,
    status: "pending",
    nombre: "Dra. Elena Sanz",
    telefono: "+34 610 456 111",
    clinica: "Vet Alameda",
    email: "elena@vetalameda.es",
    createdAt: relativeDate(0, 8, 20),
    emailEvents: [],
  },
  {
    id: "DEMO-010",
    contactId: "CNT-010",
    date: relativeDate(4, 16, 0),
    time: "16:00",
    duration: 45,
    status: "confirmed",
    nombre: "Clínica Montecelo",
    telefono: "+34 645 900 321",
    clinica: "Montecelo Vet",
    email: "direccion@montecelovet.com",
    createdAt: relativeDate(0, 9, 50),
    emailEvents: [
      {
        category: "booking_confirmed",
        subject: "Demo confirmada para la próxima semana",
        intendedRecipient: "direccion@montecelovet.com",
        deliveredTo: "direccion@montecelovet.com",
        status: "sent",
        error: null,
        message: "Invitación enviada.",
        sentAt: relativeDate(0, 9, 55),
      },
    ],
  },
  {
    id: "DEMO-011",
    contactId: "CNT-011",
    date: relativeDate(6, 13, 0),
    time: "13:00",
    duration: 30,
    status: "cancelled",
    nombre: "Centro Veterinario Delta",
    telefono: "+34 634 555 210",
    clinica: "Delta Pets",
    email: "equipo@deltapets.es",
    createdAt: relativeDate(0, 11, 5),
    emailEvents: [
      {
        category: "booking_cancelled",
        subject: "Actualización de tu cita demo",
        intendedRecipient: "equipo@deltapets.es",
        deliveredTo: "equipo@deltapets.es",
        status: "sent",
        error: null,
        message: "Cancelación informada al cliente.",
        sentAt: relativeDate(0, 11, 20),
      },
    ],
  },
  {
    id: "DEMO-017",
    contactId: "CNT-017",
    date: currentMonthDate(2, 10, 0),
    time: "10:00",
    duration: 30,
    status: "confirmed",
    nombre: "Clínica Río",
    telefono: "+34 611 101 201",
    clinica: "Río Vet",
    email: "equipo@riovet.es",
    createdAt: relativeDate(-8, 10, 10),
    emailEvents: [],
  },
  {
    id: "DEMO-018",
    contactId: "CNT-018",
    date: currentMonthDate(5, 12, 30),
    time: "12:30",
    duration: 30,
    status: "pending",
    nombre: "Dr. Jaime Pardo",
    telefono: "+34 611 301 401",
    clinica: "Pardo Animal",
    email: "jaime@pardoanimal.es",
    createdAt: relativeDate(-7, 9, 20),
    emailEvents: [],
  },
  {
    id: "DEMO-019",
    contactId: "CNT-019",
    date: currentMonthDate(8, 16, 0),
    time: "16:00",
    duration: 45,
    status: "cancelled",
    nombre: "Vet Serena",
    telefono: "+34 612 401 402",
    clinica: "Serena Pets",
    email: "direccion@serenapets.es",
    createdAt: relativeDate(-6, 11, 30),
    emailEvents: [],
  },
  {
    id: "DEMO-020",
    contactId: "CNT-020",
    date: currentMonthDate(12, 11, 30),
    time: "11:30",
    duration: 30,
    status: "confirmed",
    nombre: "Clínica Prado",
    telefono: "+34 613 555 210",
    clinica: "Prado Vet",
    email: "recepcion@pradovet.es",
    createdAt: relativeDate(-5, 10, 0),
    emailEvents: [],
  },
  {
    id: "DEMO-021",
    contactId: "CNT-021",
    date: currentMonthDate(18, 9, 30),
    time: "09:30",
    duration: 30,
    status: "expired",
    nombre: "Centro Pet Azul",
    telefono: "+34 614 203 908",
    clinica: "Pet Azul",
    email: "agenda@petazul.es",
    createdAt: relativeDate(-4, 8, 40),
    emailEvents: [],
  },
  {
    id: "DEMO-022",
    contactId: "CNT-022",
    date: currentMonthDate(18, 13, 0),
    time: "13:00",
    duration: 30,
    status: "rescheduled",
    nombre: "Clínica Bosque",
    telefono: "+34 615 112 778",
    clinica: "Bosque Vet",
    email: "direccion@bosquevet.es",
    createdAt: relativeDate(-4, 13, 20),
    emailEvents: [],
  },
  {
    id: "DEMO-023",
    contactId: "CNT-023",
    date: currentMonthDate(18, 17, 0),
    time: "17:00",
    duration: 45,
    status: "cancelled",
    nombre: "Dra. Nora Vidal",
    telefono: "+34 616 909 101",
    clinica: "Vidal Animal Care",
    email: "nora@vidalanimal.es",
    createdAt: relativeDate(-3, 12, 15),
    emailEvents: [],
  },
  {
    id: "DEMO-024",
    contactId: "CNT-024",
    date: currentMonthDate(18, 18, 30),
    time: "18:30",
    duration: 30,
    status: "pending",
    nombre: "Clínica Mar",
    telefono: "+34 617 000 321",
    clinica: "Mar Vet",
    email: "equipo@marvet.es",
    createdAt: relativeDate(-3, 14, 0),
    emailEvents: [],
  },
  {
    id: "DEMO-025",
    contactId: "CNT-025",
    date: currentMonthDate(20, 10, 0),
    time: "10:00",
    duration: 30,
    status: "confirmed",
    nombre: "Vet Horizonte Norte",
    telefono: "+34 618 234 567",
    clinica: "Horizonte Norte",
    email: "hola@horizontenorte.es",
    createdAt: relativeDate(-2, 10, 25),
    emailEvents: [],
  },
  {
    id: "DEMO-026",
    contactId: "CNT-026",
    date: currentMonthDate(23, 12, 0),
    time: "12:00",
    duration: 30,
    status: "pending",
    nombre: "Clínica Faro",
    telefono: "+34 619 876 543",
    clinica: "Faro Pets",
    email: "direccion@faropets.es",
    createdAt: relativeDate(-2, 11, 10),
    emailEvents: [],
  },
  {
    id: "DEMO-027",
    contactId: "CNT-027",
    date: currentMonthDate(24, 17, 30),
    time: "17:30",
    duration: 60,
    status: "confirmed",
    nombre: "Dr. Hugo León",
    telefono: "+34 620 654 321",
    clinica: "León Animal",
    email: "hugo@leonanimal.es",
    createdAt: relativeDate(-1, 16, 20),
    emailEvents: [],
  },
  {
    id: "DEMO-028",
    contactId: "CNT-028",
    date: currentMonthDate(27, 11, 0),
    time: "11:00",
    duration: 30,
    status: "rescheduled",
    nombre: "Clínica Valle",
    telefono: "+34 621 432 765",
    clinica: "Valle Vet",
    email: "agenda@vallevet.es",
    createdAt: relativeDate(-1, 9, 55),
    emailEvents: [],
  },
]
}

export function createDemoBookings() {
  const conversationFixtures = createDemoConversationFixtures()
  const demoBookingFixtures = createDemoBookingFixtures()
  return demoBookingFixtures.map(({ contactId, ...booking }) => {
    void contactId
    return {
      ...booking,
      ...(conversationFixtures[booking.id as keyof typeof conversationFixtures] || {}),
    }
  })
}

export function createDemoContacts() {
  const demoBookingFixtures = createDemoBookingFixtures()
  return [
  {
    id: "CNT-001",
    nombre: "Dra. Ana Martín",
    email: "ana@clinicacentral.com",
    telefono: "+34 612 345 678",
    clinica: "Clínica Central",
    mensaje: "Quiero revisar integración con agenda y recordatorios automáticos.",
    roi: {
      monthlyPatients: 420,
      averageTicket: 68,
      conversionLoss: 16,
      roi: 230,
    },
    booking: demoBookingFixtures.find((item) => item.contactId === "CNT-001")
      ? {
          id: "DEMO-001",
          date: demoBookingFixtures.find((item) => item.contactId === "CNT-001")!.date,
          time: "10:00",
          duration: 30,
          status: "confirmed",
        }
      : null,
    createdAt: relativeDate(-2, 9, 12),
  },
  {
    id: "CNT-002",
    nombre: "Dr. Luis Pérez",
    email: "luis@vetnorte.es",
    telefono: "+34 611 222 333",
    clinica: "Vet Norte",
    mensaje: "Nos interesa automatizar captación y seguimiento comercial.",
    roi: {
      monthlyPatients: 260,
      averageTicket: 59,
      conversionLoss: 12,
      roi: 145,
    },
    booking: {
      id: "DEMO-002",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-002")!.date,
      time: "12:30",
      duration: 30,
      status: "pending",
    },
    createdAt: relativeDate(-1, 10, 28),
  },
  {
    id: "CNT-003",
    nombre: "Dra. Marta Ruiz",
    email: "direccion@hospitalvetsur.com",
    telefono: "+34 644 111 000",
    clinica: "Hospital Vet Sur",
    mensaje: "Necesitamos priorizar urgencias y responder en menos de 5 minutos.",
    roi: {
      monthlyPatients: 510,
      averageTicket: 75,
      conversionLoss: 22,
      roi: 280,
    },
    booking: {
      id: "DEMO-003",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-003")!.date,
      time: "17:30",
      duration: 45,
      status: "confirmed",
    },
    createdAt: relativeDate(-1, 12, 18),
  },
  {
    id: "CNT-004",
    nombre: "Clínica Aurora",
    email: "gerencia@auroravet.es",
    telefono: "+34 622 001 110",
    clinica: "Aurora Vet",
    mensaje: "Queremos validar el flujo de agenda antes de movernos a producción.",
    roi: {
      monthlyPatients: 180,
      averageTicket: 54,
      conversionLoss: 9,
      roi: 120,
    },
    booking: {
      id: "DEMO-004",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-004")!.date,
      time: "11:30",
      duration: 30,
      status: "confirmed",
    },
    createdAt: relativeDate(-1, 12, 50),
  },
  {
    id: "CNT-005",
    nombre: "Centro Vet Levante",
    email: "info@levantepets.es",
    telefono: "+34 633 444 777",
    clinica: "Levante Pets",
    mensaje: "Nos interesa pero no llegamos a confirmar la demo.",
    roi: {
      monthlyPatients: 140,
      averageTicket: 50,
      conversionLoss: 18,
      roi: 98,
    },
    booking: {
      id: "DEMO-005",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-005")!.date,
      time: "16:30",
      duration: 30,
      status: "expired",
    },
    createdAt: relativeDate(-3, 16, 30),
  },
  {
    id: "CNT-006",
    nombre: "Dr. Pablo Ortega",
    email: "pablo@ortegaanimal.com",
    telefono: "+34 600 999 123",
    clinica: "Ortega Animal Care",
    mensaje: "Queremos soporte multi-sede y embudo por canal.",
    roi: {
      monthlyPatients: 350,
      averageTicket: 72,
      conversionLoss: 15,
      roi: 210,
    },
    booking: {
      id: "DEMO-006",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-006")!.date,
      time: "18:00",
      duration: 60,
      status: "pending",
    },
    createdAt: relativeDate(-1, 8, 40),
  },
  {
    id: "CNT-015",
    nombre: "Clínica Sierra",
    email: "direccion@sierravet.es",
    telefono: "+34 623 456 780",
    clinica: "Sierra Vet",
    mensaje: "La demo quedó pendiente y terminó expirando el día anterior.",
    roi: {
      monthlyPatients: 190,
      averageTicket: 57,
      conversionLoss: 14,
      roi: 118,
    },
    booking: {
      id: "DEMO-015",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-015")!.date,
      time: "11:00",
      duration: 30,
      status: "rescheduled",
    },
    createdAt: relativeDate(-2, 18, 0),
  },
  {
    id: "CNT-016",
    nombre: "Clínica Sierra",
    email: "direccion@sierravet.es",
    telefono: "+34 623 456 780",
    clinica: "Sierra Vet",
    mensaje: "Nueva demo agendada después de una cita previa que expiró.",
    roi: {
      monthlyPatients: 205,
      averageTicket: 60,
      conversionLoss: 13,
      roi: 126,
    },
    booking: {
      id: "DEMO-016",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-016")!.date,
      time: "10:30",
      duration: 30,
      status: "rescheduled",
    },
    createdAt: relativeDate(0, 10, 0),
  },
  {
    id: "CNT-007",
    nombre: "Dra. Carla Ibañez",
    email: "carla@vetcosta.es",
    telefono: "+34 620 202 202",
    clinica: "Clínica Vet Costa",
    mensaje: "Necesitamos automatizar recordatorios de vacunas y revisiones.",
    roi: {
      monthlyPatients: 290,
      averageTicket: 63,
      conversionLoss: 11,
      roi: 170,
    },
    booking: {
      id: "DEMO-007",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-007")!.date,
      time: "19:00",
      duration: 30,
      status: "confirmed",
    },
    createdAt: relativeDate(-1, 10, 1),
  },
  {
    id: "CNT-008",
    nombre: "Grupo Veterinario Atlántico",
    email: "direccion@atlanticovet.com",
    telefono: "+34 699 101 101",
    clinica: "Atlántico Vet",
    mensaje: "Necesitamos un piloto para 3 clínicas con reporting centralizado.",
    roi: {
      monthlyPatients: 780,
      averageTicket: 88,
      conversionLoss: 20,
      roi: 315,
    },
    booking: {
      id: "DEMO-008",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-008")!.date,
      time: "12:00",
      duration: 45,
      status: "confirmed",
    },
    createdAt: relativeDate(-1, 11, 45),
  },
  {
    id: "CNT-009",
    nombre: "Dra. Elena Sanz",
    email: "elena@vetalameda.es",
    telefono: "+34 610 456 111",
    clinica: "Vet Alameda",
    mensaje: "Queremos probar un flujo más rápido para leads de urgencias.",
    roi: {
      monthlyPatients: 240,
      averageTicket: 61,
      conversionLoss: 14,
      roi: 162,
    },
    booking: {
      id: "DEMO-009",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-009")!.date,
      time: "09:30",
      duration: 30,
      status: "pending",
    },
    createdAt: relativeDate(0, 8, 15),
  },
  {
    id: "CNT-010",
    nombre: "Clínica Montecelo",
    email: "direccion@montecelovet.com",
    telefono: "+34 645 900 321",
    clinica: "Montecelo Vet",
    mensaje: "Nos interesa montar un piloto de activación comercial durante abril.",
    roi: {
      monthlyPatients: 330,
      averageTicket: 70,
      conversionLoss: 13,
      roi: 205,
    },
    booking: {
      id: "DEMO-010",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-010")!.date,
      time: "16:00",
      duration: 45,
      status: "confirmed",
    },
    createdAt: relativeDate(0, 9, 45),
  },
  {
    id: "CNT-011",
    nombre: "Centro Veterinario Delta",
    email: "equipo@deltapets.es",
    telefono: "+34 634 555 210",
    clinica: "Delta Pets",
    mensaje: "Tuvimos que cancelar por reajuste del equipo de recepción.",
    roi: {
      monthlyPatients: 210,
      averageTicket: 57,
      conversionLoss: 10,
      roi: 132,
    },
    booking: {
      id: "DEMO-011",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-011")!.date,
      time: "13:00",
      duration: 30,
      status: "cancelled",
    },
    createdAt: relativeDate(0, 11, 0),
  },
  {
    id: "CNT-012",
    nombre: "Clínica Nova",
    email: "agenda@novapets.es",
    telefono: "+34 621 987 654",
    clinica: "Nova Pets",
    mensaje: "Hemos cancelado la demo de hoy por un cambio interno de última hora.",
    roi: {
      monthlyPatients: 195,
      averageTicket: 56,
      conversionLoss: 9,
      roi: 126,
    },
    booking: {
      id: "DEMO-012",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-012")!.date,
      time: "19:00",
      duration: 30,
      status: "cancelled",
    },
    createdAt: relativeDate(0, 12, 40),
  },
  {
    id: "CNT-013",
    nombre: "Clínica Horizonte",
    email: "direccion@horizontevet.es",
    telefono: "+34 622 778 991",
    clinica: "Horizonte Vet",
    mensaje: "Queremos evaluar la agenda centralizada y el seguimiento de primeras visitas.",
    roi: {
      monthlyPatients: 305,
      averageTicket: 66,
      conversionLoss: 12,
      roi: 184,
    },
    booking: {
      id: "DEMO-013",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-013")!.date,
      time: "14:00",
      duration: 30,
      status: "confirmed",
    },
    createdAt: relativeDate(0, 9, 0),
  },
  {
    id: "CNT-014",
    nombre: "Dr. Sergio Molina",
    email: "sergio@molinaanimal.es",
    telefono: "+34 611 808 707",
    clinica: "Molina Animal",
    mensaje: "Nos interesa reducir el tiempo de respuesta a leads entrantes.",
    roi: {
      monthlyPatients: 225,
      averageTicket: 58,
      conversionLoss: 11,
      roi: 141,
    },
    booking: {
      id: "DEMO-014",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-014")!.date,
      time: "15:30",
      duration: 30,
      status: "pending",
    },
    createdAt: relativeDate(0, 9, 35),
  },
  {
    id: "CNT-017",
    nombre: "Clínica Río",
    email: "equipo@riovet.es",
    telefono: "+34 611 101 201",
    clinica: "Río Vet",
    mensaje: "Queremos revisar la agenda automatizada para primeras visitas.",
    roi: { monthlyPatients: 210, averageTicket: 56, conversionLoss: 10, roi: 134 },
    booking: {
      id: "DEMO-017",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-017")!.date,
      time: "10:00",
      duration: 30,
      status: "confirmed",
    },
    createdAt: relativeDate(-8, 10, 5),
  },
  {
    id: "CNT-018",
    nombre: "Dr. Jaime Pardo",
    email: "jaime@pardoanimal.es",
    telefono: "+34 611 301 401",
    clinica: "Pardo Animal",
    mensaje: "Nos interesa reducir tiempos muertos en agenda.",
    roi: { monthlyPatients: 175, averageTicket: 52, conversionLoss: 11, roi: 112 },
    booking: {
      id: "DEMO-018",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-018")!.date,
      time: "12:30",
      duration: 30,
      status: "pending",
    },
    createdAt: relativeDate(-7, 9, 15),
  },
  {
    id: "CNT-019",
    nombre: "Vet Serena",
    email: "direccion@serenapets.es",
    telefono: "+34 612 401 402",
    clinica: "Serena Pets",
    mensaje: "Se canceló por indisponibilidad del equipo.",
    roi: { monthlyPatients: 240, averageTicket: 61, conversionLoss: 9, roi: 144 },
    booking: {
      id: "DEMO-019",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-019")!.date,
      time: "16:00",
      duration: 45,
      status: "cancelled",
    },
    createdAt: relativeDate(-6, 11, 25),
  },
  {
    id: "CNT-020",
    nombre: "Clínica Prado",
    email: "recepcion@pradovet.es",
    telefono: "+34 613 555 210",
    clinica: "Prado Vet",
    mensaje: "Queremos automatizar captación local.",
    roi: { monthlyPatients: 280, averageTicket: 64, conversionLoss: 13, roi: 171 },
    booking: {
      id: "DEMO-020",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-020")!.date,
      time: "11:30",
      duration: 30,
      status: "confirmed",
    },
    createdAt: relativeDate(-5, 9, 55),
  },
  {
    id: "CNT-021",
    nombre: "Centro Pet Azul",
    email: "agenda@petazul.es",
    telefono: "+34 614 203 908",
    clinica: "Pet Azul",
    mensaje: "La cita expiró sin confirmación final.",
    roi: { monthlyPatients: 160, averageTicket: 49, conversionLoss: 15, roi: 101 },
    booking: {
      id: "DEMO-021",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-021")!.date,
      time: "09:30",
      duration: 30,
      status: "expired",
    },
    createdAt: relativeDate(-4, 8, 35),
  },
  {
    id: "CNT-022",
    nombre: "Clínica Bosque",
    email: "direccion@bosquevet.es",
    telefono: "+34 615 112 778",
    clinica: "Bosque Vet",
    mensaje: "La cita anterior se movió a otra fecha.",
    roi: { monthlyPatients: 225, averageTicket: 58, conversionLoss: 12, roi: 139 },
    booking: {
      id: "DEMO-022",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-022")!.date,
      time: "13:00",
      duration: 30,
      status: "rescheduled",
    },
    createdAt: relativeDate(-4, 13, 15),
  },
  {
    id: "CNT-023",
    nombre: "Dra. Nora Vidal",
    email: "nora@vidalanimal.es",
    telefono: "+34 616 909 101",
    clinica: "Vidal Animal Care",
    mensaje: "Hubo que cancelar por reunión clínica.",
    roi: { monthlyPatients: 205, averageTicket: 55, conversionLoss: 10, roi: 123 },
    booking: {
      id: "DEMO-023",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-023")!.date,
      time: "17:00",
      duration: 45,
      status: "cancelled",
    },
    createdAt: relativeDate(-3, 12, 10),
  },
  {
    id: "CNT-024",
    nombre: "Clínica Mar",
    email: "equipo@marvet.es",
    telefono: "+34 617 000 321",
    clinica: "Mar Vet",
    mensaje: "Pendiente de validar el flujo comercial.",
    roi: { monthlyPatients: 190, averageTicket: 53, conversionLoss: 11, roi: 119 },
    booking: {
      id: "DEMO-024",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-024")!.date,
      time: "18:30",
      duration: 30,
      status: "pending",
    },
    createdAt: relativeDate(-3, 13, 55),
  },
  {
    id: "CNT-025",
    nombre: "Vet Horizonte Norte",
    email: "hola@horizontenorte.es",
    telefono: "+34 618 234 567",
    clinica: "Horizonte Norte",
    mensaje: "Queremos más volumen de primeras consultas.",
    roi: { monthlyPatients: 320, averageTicket: 67, conversionLoss: 14, roi: 196 },
    booking: {
      id: "DEMO-025",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-025")!.date,
      time: "10:00",
      duration: 30,
      status: "confirmed",
    },
    createdAt: relativeDate(-2, 10, 20),
  },
  {
    id: "CNT-026",
    nombre: "Clínica Faro",
    email: "direccion@faropets.es",
    telefono: "+34 619 876 543",
    clinica: "Faro Pets",
    mensaje: "Queremos comparar campañas y agenda en el mismo panel.",
    roi: { monthlyPatients: 260, averageTicket: 62, conversionLoss: 12, roi: 158 },
    booking: {
      id: "DEMO-026",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-026")!.date,
      time: "12:00",
      duration: 30,
      status: "pending",
    },
    createdAt: relativeDate(-2, 11, 5),
  },
  {
    id: "CNT-027",
    nombre: "Dr. Hugo León",
    email: "hugo@leonanimal.es",
    telefono: "+34 620 654 321",
    clinica: "León Animal",
    mensaje: "Buscamos automatizar seguimiento post-visita.",
    roi: { monthlyPatients: 340, averageTicket: 71, conversionLoss: 13, roi: 208 },
    booking: {
      id: "DEMO-027",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-027")!.date,
      time: "17:30",
      duration: 60,
      status: "confirmed",
    },
    createdAt: relativeDate(-1, 16, 15),
  },
  {
    id: "CNT-028",
    nombre: "Clínica Valle",
    email: "agenda@vallevet.es",
    telefono: "+34 621 432 765",
    clinica: "Valle Vet",
    mensaje: "La agenda previa terminó reagendada a una nueva fecha.",
    roi: { monthlyPatients: 215, averageTicket: 57, conversionLoss: 12, roi: 131 },
    booking: {
      id: "DEMO-028",
      date: demoBookingFixtures.find((item) => item.contactId === "CNT-028")!.date,
      time: "11:00",
      duration: 30,
      status: "rescheduled",
    },
    createdAt: relativeDate(-1, 9, 50),
  },
]
}

export const DEMO_BOOKINGS = createDemoBookings()
export const DEMO_CONTACTS = createDemoContacts()

export const DEMO_ADMIN_USERS: Array<{
  id: string
  email: string
  name: string
  role: AdminRole
  status: "active" | "disabled"
  createdAt: string
}> = [
  {
    id: "USR-DEMO-001",
    email: "superadmin@clinvetia.com",
    name: "Super Admin Demo",
    role: "superadmin",
    status: "active",
    createdAt: "2026-01-05T09:00:00.000Z",
  },
  {
    id: "USR-DEMO-002",
    email: "admin@clinvetia.com",
    name: "Admin Operaciones",
    role: "admin",
    status: "active",
    createdAt: "2026-01-08T10:20:00.000Z",
  },
  {
    id: "USR-DEMO-003",
    email: "manager@clinvetia.com",
    name: "Manager Comercial",
    role: "manager",
    status: "active",
    createdAt: "2026-01-10T11:10:00.000Z",
  },
  {
    id: "USR-DEMO-004",
    email: "worker@clinvetia.com",
    name: "Operador SDR",
    role: "worker",
    status: "active",
    createdAt: "2026-01-12T12:00:00.000Z",
  },
  {
    id: "USR-DEMO-005",
    email: "worker-disabled@clinvetia.com",
    name: "Operador Inactivo",
    role: "worker",
    status: "disabled",
    createdAt: "2026-01-13T12:30:00.000Z",
  },
  {
    id: "USR-DEMO-006",
    email: "demo@clinvetia.com",
    name: "Usuario Demo",
    role: "demo",
    status: "active",
    createdAt: "2026-01-01T08:00:00.000Z",
  },
]

export const DEMO_PENDING_USER_ACTIONS: Array<{
  id: string
  type: "invite_user" | "reset_user_password"
  email: string
  name: string
  role: AdminRole | null
  targetUserId: string | null
  createdAt: string
  expiresAt: string
  requestedByRole: AdminRole
  status: "pending"
}> = [
  {
    id: "ACT-DEMO-001",
    type: "invite_user",
    email: "nuevo.manager@clinvetia.com",
    name: "Nuevo Manager",
    role: "manager",
    targetUserId: null,
    createdAt: "2026-03-03T09:20:00.000Z",
    expiresAt: "2026-03-05T09:20:00.000Z",
    requestedByRole: "admin",
    status: "pending",
  },
  {
    id: "ACT-DEMO-002",
    type: "invite_user",
    email: "nuevo.worker@clinvetia.com",
    name: "Nuevo Worker",
    role: "worker",
    targetUserId: null,
    createdAt: "2026-03-03T09:45:00.000Z",
    expiresAt: "2026-03-05T09:45:00.000Z",
    requestedByRole: "manager",
    status: "pending",
  },
  {
    id: "ACT-DEMO-003",
    type: "reset_user_password",
    email: "worker-disabled@clinvetia.com",
    name: "Operador Inactivo",
    role: null,
    targetUserId: "USR-DEMO-005",
    createdAt: "2026-03-03T10:10:00.000Z",
    expiresAt: "2026-03-04T10:10:00.000Z",
    requestedByRole: "admin",
    status: "pending",
  },
]

export const DEMO_AUDIT_EVENTS = [
  {
    id: "AUD-DEMO-001",
    adminId: "USR-DEMO-001",
    action: "INVITE_USER",
    targetType: "user_invitation",
    targetId: "ACT-DEMO-001",
    metadata: { email: "nuevo.manager@clinvetia.com", role: "manager" },
    createdAt: "2026-03-03T09:20:10.000Z",
  },
  {
    id: "AUD-DEMO-002",
    adminId: "USR-DEMO-002",
    action: "INVITE_USER",
    targetType: "user_invitation",
    targetId: "ACT-DEMO-002",
    metadata: { email: "nuevo.worker@clinvetia.com", role: "worker" },
    createdAt: "2026-03-03T09:45:18.000Z",
  },
  {
    id: "AUD-DEMO-003",
    adminId: "USR-DEMO-002",
    action: "REQUEST_RESET_PASSWORD",
    targetType: "user",
    targetId: "USR-DEMO-005",
    metadata: { email: "worker-disabled@clinvetia.com" },
    createdAt: "2026-03-03T10:10:22.000Z",
  },
  {
    id: "AUD-DEMO-004",
    adminId: "USR-DEMO-004",
    action: "SEND_CUSTOMER_EMAIL",
    targetType: "booking",
    targetId: "DEMO-004",
    metadata: { deliveredTo: "gerencia@auroravet.es", status: "sent" },
    createdAt: "2026-03-03T14:20:40.000Z",
  },
  {
    id: "AUD-DEMO-005",
    adminId: "USR-DEMO-003",
    action: "RESCHEDULE_BOOKING",
    targetType: "booking",
    targetId: "DEMO-006",
    metadata: { from: "18:00", to: "18:30" },
    createdAt: "2026-03-03T15:03:02.000Z",
  },
]

export const DEMO_MAIL_MESSAGES = [
  {
    id: "mail-demo-001",
    mailboxType: "shared",
    mailboxEmail: "info@clinvetia.com",
    folder: "inbox",
    direction: "inbound",
    status: "received",
    from: { email: "ana@clinicacentral.com", name: "Dra. Ana Martín" },
    to: [{ email: "info@clinvetia.com", name: "Clinvetia" }],
    subject: "Consulta sobre integración con agenda",
    body: "Hola equipo, nos gustaría ver cómo se integra ClinvetIA con nuestra agenda actual y qué tiempos de implantación manejáis.",
    preview: "Hola equipo, nos gustaría ver cómo se integra ClinvetIA con nuestra agenda actual...",
    createdAt: "2026-02-28T10:18:00.000Z",
    updatedAt: "2026-02-28T10:18:00.000Z",
    error: null,
  },
  {
    id: "mail-demo-002",
    mailboxType: "shared",
    mailboxEmail: "info@clinvetia.com",
    folder: "inbox",
    direction: "inbound",
    status: "received",
    from: { email: "luis@vetnorte.es", name: "Dr. Luis Pérez" },
    to: [{ email: "info@clinvetia.com", name: "Clinvetia" }],
    subject: "Reagendar la demo del jueves",
    body: "Buenas, ¿podemos mover la demo del jueves a primera hora del viernes? Gracias.",
    preview: "Buenas, ¿podemos mover la demo del jueves a primera hora del viernes?",
    createdAt: "2026-02-27T16:30:00.000Z",
    updatedAt: "2026-02-27T16:30:00.000Z",
    error: null,
  },
  {
    id: "mail-demo-003",
    mailboxType: "shared",
    mailboxEmail: "info@clinvetia.com",
    folder: "sent",
    direction: "outbound",
    status: "sent",
    from: { email: "info@clinvetia.com", name: "Equipo Clinvetia" },
    to: [{ email: "ana@clinicacentral.com", name: "Dra. Ana Martín" }],
    subject: "Confirmación de demo personalizada",
    body: "Hola Ana, te confirmamos la demo para el martes a las 10:00. Te enviamos el enlace y detalles en este correo.",
    preview: "Hola Ana, te confirmamos la demo para el martes a las 10:00...",
    createdAt: "2026-02-26T09:05:00.000Z",
    updatedAt: "2026-02-26T09:05:00.000Z",
    error: null,
  },
  {
    id: "mail-demo-004",
    mailboxType: "user",
    mailboxEmail: "demo@clinvetia.com",
    folder: "sent",
    direction: "outbound",
    status: "failed",
    from: { email: "demo@clinvetia.com", name: "Usuario Demo" },
    to: [{ email: "direccion@hospitalvetsur.com", name: "Hospital Vet Sur" }],
    subject: "Seguimiento de propuesta",
    body: "Te compartimos de nuevo la propuesta de automatización. Quedamos pendientes de tus comentarios.",
    preview: "Te compartimos de nuevo la propuesta de automatización...",
    createdAt: "2026-02-25T13:40:00.000Z",
    updatedAt: "2026-02-25T13:40:00.000Z",
    error: "SMTP timeout (simulado en demo)",
  },
  {
    id: "mail-demo-005",
    mailboxType: "user",
    mailboxEmail: "demo@clinvetia.com",
    folder: "trash",
    direction: "inbound",
    status: "received",
    from: { email: "newsletter@partner-vet.io", name: "Partner Vet" },
    to: [{ email: "demo@clinvetia.com", name: "Usuario Demo" }],
    subject: "Newsletter mensual",
    body: "Resumen de novedades del sector veterinario.",
    preview: "Resumen de novedades del sector veterinario.",
    createdAt: "2026-02-20T08:00:00.000Z",
    updatedAt: "2026-02-20T08:00:00.000Z",
    error: null,
  },
]
